sudo: required

services:
    - docker

before_install:
    - docker build -t stanfeldman/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true stanfeldman/react-test npm test

after_success:
    # build images
    - docker build -t stanfeldman/multi-client ./client
    - docker build -t stanfeldman/multi-nginx ./nginx
    - docker build -t stanfeldman/multi-server ./server
    - docker build -t stanfeldman/multi-worker ./worker
    
    # login to docker
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

    # push to docker hub
    - docker push stanfeldman/multi-client
    - docker push stanfeldman/multi-nginx
    - docker push stanfeldman/multi-server
    - docker push stanfeldman/multi-worker